
import { supabase } from "@/integrations/supabase/client";
import { toast } from "@/hooks/use-toast";
import { OrderFormData } from "@/types/order";

export function useOrderSubmission(
  orderDetails: OrderFormData,
  components: Record<string, any>,
  customComponents: any[],
  setSubmitting: (submitting: boolean) => void,
  inventoryItems: any[] | undefined
) {
  const updateInventoryStock = async (orderId: string) => {
    // Skip if no inventory items are loaded
    if (!inventoryItems) return;
    
    // Collect all materials and their consumption
    const materialUsage: Record<string, number> = {};
    
    // Process standard components
    Object.values(components).forEach(comp => {
      if (comp.material_id && comp.consumption) {
        const materialId = comp.material_id;
        const consumption = parseFloat(String(comp.consumption));
        
        if (!isNaN(consumption)) {
          if (!materialUsage[materialId]) {
            materialUsage[materialId] = consumption;
          } else {
            materialUsage[materialId] += consumption;
          }
        }
      }
    });
    
    // Process custom components
    customComponents.forEach(comp => {
      if (comp.material_id && comp.consumption) {
        const materialId = comp.material_id;
        const consumption = parseFloat(String(comp.consumption));
        
        if (!isNaN(consumption)) {
          if (!materialUsage[materialId]) {
            materialUsage[materialId] = consumption;
          } else {
            materialUsage[materialId] += consumption;
          }
        }
      }
    });
    
    console.log("Material usage for inventory update:", materialUsage);
    
    // Update inventory for each used material
    for (const [materialId, usage] of Object.entries(materialUsage)) {
      try {
        // Get current inventory level
        const { data: material, error: fetchError } = await supabase
          .from('inventory')
          .select('quantity')
          .eq('id', materialId)
          .single();
        
        if (fetchError) {
          console.error(`Error fetching inventory for material ${materialId}:`, fetchError);
          continue;
        }
        
        // Calculate new quantity
        const currentQuantity = material.quantity || 0;
        const newQuantity = currentQuantity - usage;
        
        // Update inventory
        const { error: updateError } = await supabase
          .from('inventory')
          .update({ quantity: newQuantity >= 0 ? newQuantity : 0 })
          .eq('id', materialId);
        
        if (updateError) {
          console.error(`Error updating inventory for material ${materialId}:`, updateError);
          toast({
            title: "Warning",
            description: `Could not update inventory for material ID: ${materialId}`,
            variant: "destructive"
          });
        } else {
          console.log(`Updated inventory for material ${materialId}: ${currentQuantity} - ${usage} = ${newQuantity}`);
          
          // Create transaction record for material usage
          const { error: transactionError } = await supabase
            .from('inventory_transactions')
            .insert({
              material_id: materialId,
              quantity: usage,
              transaction_type: 'order_consumption',
              reference_id: orderId,
              notes: `Material consumed for order ${orderDetails.company_name || 'Unknown'}`
            });
            
          if (transactionError) {
            console.error(`Error creating inventory transaction record:`, transactionError);
          }
        }
      } catch (error) {
        console.error(`Error processing material ${materialId}:`, error);
      }
    }
  };

  const handleSubmit = async (e: React.FormEvent): Promise<string | undefined> => {
    e.preventDefault();
    
    setSubmitting(true);
    
    try {
      // Prepare data for database insert
      const orderData = {
        company_name: orderDetails.company_id ? null : orderDetails.company_name,
        company_id: orderDetails.company_id,
        quantity: parseInt(orderDetails.quantity),
        bag_length: parseFloat(orderDetails.bag_length),
        bag_width: parseFloat(orderDetails.bag_width),
        rate: orderDetails.rate ? parseFloat(orderDetails.rate) : null,
        order_date: orderDetails.order_date,
        sales_account_id: orderDetails.sales_account_id || null,
        special_instructions: orderDetails.special_instructions || null
      };

      console.log("Submitting order data:", orderData);
      
      // Insert the order - using type assertion to bypass the order_number requirement
      // since this is auto-generated by the database trigger
      const { data: orderResult, error: orderError } = await supabase
        .from("orders")
        .insert(orderData as any)
        .select('id, order_number')
        .single();
      
      if (orderError) {
        console.error("Order insertion error:", orderError);
        throw orderError;
      }
      
      console.log("Order created successfully:", orderResult);
      
      // Process components if any exist
      const allComponents = [
        ...Object.values(components).filter(Boolean),
        ...customComponents
      ].filter(Boolean);
      
      console.log("Components to be saved:", allComponents);
      
      if (allComponents.length > 0) {
        const componentsToInsert = allComponents.map(comp => ({
          order_id: orderResult.id,
          component_type: comp.type === 'custom' ? 'custom' : comp.type,
          size: comp.length && comp.width ? `${comp.length}x${comp.width}` : null,
          color: comp.color || null,
          gsm: comp.gsm || null,
          custom_name: comp.type === 'custom' ? (comp.custom_name || comp.customName) : null,
          material_id: comp.material_id || null,
          roll_width: comp.roll_width ? parseFloat(String(comp.roll_width)) : null,
          consumption: comp.consumption ? parseFloat(String(comp.consumption)) : null
        }));

        console.log("Inserting components:", componentsToInsert);

        const { error: componentsError } = await supabase
          .from("order_components")
          .insert(componentsToInsert);
        
        if (componentsError) {
          console.error("Error saving components:", componentsError);
          toast({
            title: "Error saving components",
            description: componentsError.message,
            variant: "destructive"
          });
        } else {
          console.log("Components saved successfully");
          
          // Update inventory stock levels
          await updateInventoryStock(orderResult.id);
        }
      }
      
      toast({
        title: "Order created successfully",
        description: `Order number: ${orderResult.order_number}`
      });

      return orderResult.id;
      
    } catch (error: any) {
      console.error("Error creating order:", error);
      toast({
        title: "Error creating order",
        description: error.message || "An unexpected error occurred",
        variant: "destructive"
      });
    } finally {
      setSubmitting(false);
    }
  };

  return { handleSubmit };
}
