-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.catalog (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  description text,
  bag_length numeric NOT NULL,
  bag_width numeric NOT NULL,
  default_quantity integer,
  default_rate numeric,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  cutting_charge numeric DEFAULT 0,
  printing_charge numeric DEFAULT 0,
  stitching_charge numeric DEFAULT 0,
  transport_charge numeric DEFAULT 0,
  total_cost numeric,
  height numeric DEFAULT 0,
  border_dimension numeric DEFAULT 0,
  selling_rate numeric,
  margin numeric,
  material_cost numeric DEFAULT 0,
  CONSTRAINT catalog_pkey PRIMARY KEY (id)
);
CREATE TABLE public.catalog_component_materials (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  catalog_component_id uuid NOT NULL,
  material_id uuid NOT NULL,
  quantity_required numeric NOT NULL DEFAULT 1,
  unit text NOT NULL,
  consumption numeric,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT catalog_component_materials_pkey PRIMARY KEY (id),
  CONSTRAINT catalog_component_materials_material_id_fkey FOREIGN KEY (material_id) REFERENCES public.inventory(id),
  CONSTRAINT catalog_component_materials_catalog_component_id_fkey FOREIGN KEY (catalog_component_id) REFERENCES public.catalog_components(id)
);
CREATE TABLE public.catalog_components (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  catalog_id uuid NOT NULL,
  component_type text NOT NULL,
  size text,
  color text,
  gsm numeric,
  custom_name text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  material_id uuid,
  roll_width numeric,
  consumption numeric,
  length numeric,
  width numeric,
  material_linked boolean DEFAULT false,
  formula text,
  CONSTRAINT catalog_components_pkey PRIMARY KEY (id),
  CONSTRAINT catalog_components_catalog_id_fkey FOREIGN KEY (catalog_id) REFERENCES public.catalog(id)
);
CREATE TABLE public.companies (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  contact_person text,
  email text,
  phone text,
  address text,
  status text DEFAULT 'active'::text,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  gst_number text,
  CONSTRAINT companies_pkey PRIMARY KEY (id)
);
CREATE TABLE public.components (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  order_id uuid NOT NULL,
  type USER-DEFINED NOT NULL,
  size text,
  color text,
  gsm text,
  details text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT components_pkey PRIMARY KEY (id),
  CONSTRAINT components_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id)
);
CREATE TABLE public.cutting_components (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  component_id uuid NOT NULL,
  cutting_job_id uuid NOT NULL,
  width numeric,
  height numeric,
  counter text,
  rewinding text,
  rate numeric,
  status USER-DEFINED DEFAULT 'pending'::job_status,
  notes text,
  waste_quantity numeric,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  roll_width numeric,
  consumption numeric,
  CONSTRAINT cutting_components_pkey PRIMARY KEY (id),
  CONSTRAINT cutting_components_component_id_fkey FOREIGN KEY (component_id) REFERENCES public.order_components(id),
  CONSTRAINT cutting_components_cutting_job_id_fkey FOREIGN KEY (cutting_job_id) REFERENCES public.cutting_jobs(id)
);
CREATE TABLE public.cutting_jobs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  job_card_id uuid NOT NULL,
  roll_width numeric,
  consumption_meters numeric,
  worker_name text,
  is_internal boolean DEFAULT true,
  status USER-DEFINED DEFAULT 'pending'::job_status,
  received_quantity integer,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  CONSTRAINT cutting_jobs_pkey PRIMARY KEY (id),
  CONSTRAINT cutting_jobs_job_card_id_fkey FOREIGN KEY (job_card_id) REFERENCES public.job_cards(id)
);
CREATE TABLE public.dispatch_batches (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  order_dispatch_id uuid NOT NULL,
  batch_number integer NOT NULL,
  quantity integer NOT NULL CHECK (quantity > 0),
  delivery_date date NOT NULL,
  status text NOT NULL DEFAULT 'pending'::text,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT dispatch_batches_pkey PRIMARY KEY (id),
  CONSTRAINT dispatch_batches_order_dispatch_id_fkey FOREIGN KEY (order_dispatch_id) REFERENCES public.order_dispatches(id)
);
CREATE TABLE public.inventory (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  material_name text NOT NULL,
  color text,
  gsm text,
  quantity numeric NOT NULL DEFAULT 0,
  unit text NOT NULL,
  alternate_unit text,
  conversion_rate numeric DEFAULT 0,
  track_cost boolean DEFAULT false,
  purchase_price numeric,
  selling_price numeric,
  status text DEFAULT 'in_stock'::text,
  min_stock_level numeric,
  reorder_level numeric,
  category_id uuid,
  location_id uuid,
  supplier_id uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  rate numeric,
  reorder_quantity numeric,
  roll_width numeric,
  purchase_rate numeric,
  is_deleted boolean DEFAULT false,
  deleted_at timestamp with time zone,
  CONSTRAINT inventory_pkey PRIMARY KEY (id),
  CONSTRAINT inventory_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.suppliers(id),
  CONSTRAINT inventory_location_id_fkey FOREIGN KEY (location_id) REFERENCES public.inventory_locations(id),
  CONSTRAINT inventory_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.material_categories(id)
);
CREATE TABLE public.inventory_batches (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  material_id uuid NOT NULL,
  batch_number text NOT NULL,
  quantity numeric NOT NULL,
  unit text NOT NULL,
  expiry_date date,
  manufacturing_date date,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT inventory_batches_pkey PRIMARY KEY (id),
  CONSTRAINT inventory_batches_material_id_fkey FOREIGN KEY (material_id) REFERENCES public.inventory(id)
);
CREATE TABLE public.inventory_locations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  description text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT inventory_locations_pkey PRIMARY KEY (id)
);
CREATE TABLE public.inventory_transaction_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  material_id uuid NOT NULL,
  transaction_type text NOT NULL,
  quantity numeric NOT NULL,
  previous_quantity numeric NOT NULL,
  new_quantity numeric NOT NULL,
  reference_id text,
  reference_number text,
  reference_type text,
  transaction_date timestamp with time zone DEFAULT now(),
  created_by uuid,
  notes text,
  metadata jsonb,
  CONSTRAINT inventory_transaction_log_pkey PRIMARY KEY (id),
  CONSTRAINT inventory_transaction_log_material_id_fkey FOREIGN KEY (material_id) REFERENCES public.inventory(id)
);
CREATE TABLE public.inventory_transaction_types (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  description text,
  affects_quantity boolean DEFAULT true,
  multiplier integer NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT inventory_transaction_types_pkey PRIMARY KEY (id)
);
CREATE TABLE public.inventory_transactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  material_id uuid NOT NULL,
  quantity numeric NOT NULL,
  transaction_type text NOT NULL,
  transaction_type_id uuid,
  reference_id text,
  reference_number text,
  notes text,
  unit text,
  unit_price numeric,
  total_price numeric,
  batch_id uuid,
  location_id uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  roll_width numeric,
  inventory_id uuid,
  reference_type text,
  CONSTRAINT inventory_transactions_pkey PRIMARY KEY (id),
  CONSTRAINT inventory_transactions_transaction_type_id_fkey FOREIGN KEY (transaction_type_id) REFERENCES public.inventory_transaction_types(id),
  CONSTRAINT inventory_transactions_inventory_id_fkey FOREIGN KEY (inventory_id) REFERENCES public.inventory(id),
  CONSTRAINT inventory_transactions_material_id_fkey FOREIGN KEY (material_id) REFERENCES public.inventory(id),
  CONSTRAINT inventory_transactions_location_id_fkey FOREIGN KEY (location_id) REFERENCES public.inventory_locations(id)
);
CREATE TABLE public.job_cards (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  order_id uuid NOT NULL,
  job_name text NOT NULL,
  status USER-DEFINED DEFAULT 'pending'::job_status,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  job_number text,
  notes text,
  CONSTRAINT job_cards_pkey PRIMARY KEY (id),
  CONSTRAINT job_cards_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id),
  CONSTRAINT job_cards_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id)
);
CREATE TABLE public.job_wastage (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  order_id uuid,
  job_card_id uuid,
  job_type text NOT NULL,
  job_id uuid NOT NULL UNIQUE,
  worker_name text,
  provided_quantity integer,
  received_quantity integer,
  wastage_quantity integer,
  wastage_percentage numeric,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT job_wastage_pkey PRIMARY KEY (id),
  CONSTRAINT job_wastage_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id),
  CONSTRAINT job_wastage_job_card_id_fkey FOREIGN KEY (job_card_id) REFERENCES public.job_cards(id)
);
CREATE TABLE public.material_categories (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  description text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT material_categories_pkey PRIMARY KEY (id)
);
CREATE TABLE public.material_order_usage (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  material_id uuid NOT NULL,
  order_id uuid NOT NULL,
  job_card_id uuid,
  component_id uuid,
  usage_quantity numeric NOT NULL,
  usage_date timestamp with time zone NOT NULL DEFAULT now(),
  unit text NOT NULL,
  notes text,
  CONSTRAINT material_order_usage_pkey PRIMARY KEY (id),
  CONSTRAINT material_order_usage_material_id_fkey FOREIGN KEY (material_id) REFERENCES public.inventory(id),
  CONSTRAINT material_order_usage_component_id_fkey FOREIGN KEY (component_id) REFERENCES public.order_components(id),
  CONSTRAINT material_order_usage_job_card_id_fkey FOREIGN KEY (job_card_id) REFERENCES public.job_cards(id),
  CONSTRAINT material_order_usage_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id)
);
CREATE TABLE public.material_suppliers (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  material_id uuid NOT NULL,
  supplier_id uuid NOT NULL,
  is_default boolean DEFAULT false,
  last_purchase_date timestamp with time zone,
  purchase_price numeric,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT material_suppliers_pkey PRIMARY KEY (id),
  CONSTRAINT material_suppliers_material_id_fkey FOREIGN KEY (material_id) REFERENCES public.inventory(id),
  CONSTRAINT material_suppliers_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.suppliers(id)
);
CREATE TABLE public.order_components (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  order_id uuid,
  component_type text NOT NULL CHECK (component_type = ANY (ARRAY['part'::text, 'border'::text, 'handle'::text, 'chain'::text, 'runner'::text, 'custom'::text, 'piping'::text])),
  custom_name text,
  size text,
  color text,
  gsm numeric CHECK (gsm > 0::numeric),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  material_id uuid,
  roll_width numeric,
  consumption numeric,
  from_template boolean DEFAULT false,
  component_cost numeric,
  component_cost_breakdown jsonb,
  is_custom boolean DEFAULT false,
  formula text DEFAULT 'standard'::text,
  CONSTRAINT order_components_pkey PRIMARY KEY (id),
  CONSTRAINT order_components_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id),
  CONSTRAINT fk_order_components_material_id FOREIGN KEY (material_id) REFERENCES public.inventory(id)
);
CREATE TABLE public.order_dispatches (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  order_id uuid NOT NULL,
  delivery_date date NOT NULL,
  tracking_number text,
  recipient_name text NOT NULL,
  delivery_address text NOT NULL,
  notes text,
  quality_checked boolean NOT NULL DEFAULT false,
  quantity_checked boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT order_dispatches_pkey PRIMARY KEY (id),
  CONSTRAINT order_dispatches_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id)
);
CREATE TABLE public.orders (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  order_number text NOT NULL UNIQUE,
  company_name text NOT NULL,
  quantity integer NOT NULL,
  bag_length numeric NOT NULL,
  bag_width numeric NOT NULL,
  order_date date NOT NULL DEFAULT CURRENT_DATE,
  rate numeric,
  status USER-DEFINED DEFAULT 'pending'::order_status,
  special_instructions text,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  company_id uuid,
  sales_account_id uuid,
  catalog_id uuid,
  delivery_date date,
  customer_name text,
  customer_phone text,
  customer_address text,
  description text,
  border_dimension numeric,
  margin numeric,
  material_cost numeric,
  production_cost numeric,
  total_cost numeric,
  calculated_selling_price numeric,
  template_margin numeric,
  cutting_charge numeric DEFAULT 0,
  printing_charge numeric DEFAULT 0,
  stitching_charge numeric DEFAULT 0,
  transport_charge numeric DEFAULT 0,
  CONSTRAINT orders_pkey PRIMARY KEY (id),
  CONSTRAINT orders_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT orders_sales_account_id_fkey FOREIGN KEY (sales_account_id) REFERENCES public.companies(id),
  CONSTRAINT orders_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.printing_jobs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  job_card_id uuid NOT NULL,
  pulling text,
  gsm text,
  sheet_length numeric,
  sheet_width numeric,
  print_image text,
  worker_name text,
  is_internal boolean DEFAULT true,
  status USER-DEFINED DEFAULT 'pending'::job_status,
  rate numeric,
  expected_completion_date date,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  received_quantity integer,
  CONSTRAINT printing_jobs_pkey PRIMARY KEY (id),
  CONSTRAINT printing_jobs_job_card_id_fkey FOREIGN KEY (job_card_id) REFERENCES public.job_cards(id),
  CONSTRAINT printing_jobs_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.processed_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  event_type character varying NOT NULL,
  reference_id uuid NOT NULL,
  processed_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT processed_events_pkey PRIMARY KEY (id)
);
CREATE TABLE public.product_details (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  catalog_id uuid NOT NULL,
  name text NOT NULL,
  description text,
  bag_length numeric NOT NULL,
  bag_width numeric NOT NULL,
  border_dimension numeric,
  height numeric,
  default_quantity integer,
  default_rate numeric,
  selling_rate numeric,
  total_cost numeric DEFAULT 0,
  margin numeric,
  cutting_charge numeric DEFAULT 0,
  printing_charge numeric DEFAULT 0,
  stitching_charge numeric DEFAULT 0,
  transport_charge numeric DEFAULT 0,
  material_calculation_complete boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT product_details_pkey PRIMARY KEY (id),
  CONSTRAINT product_details_catalog_id_fkey FOREIGN KEY (catalog_id) REFERENCES public.catalog(id)
);
CREATE TABLE public.product_materials (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  product_id uuid NOT NULL,
  material_id uuid NOT NULL,
  quantity_required numeric NOT NULL,
  unit text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT product_materials_pkey PRIMARY KEY (id),
  CONSTRAINT product_materials_material_id_fkey FOREIGN KEY (material_id) REFERENCES public.inventory(id),
  CONSTRAINT product_materials_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id)
);
CREATE TABLE public.products (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  description text,
  sku text,
  unit_price numeric,
  stock_quantity integer DEFAULT 0,
  category text,
  status text DEFAULT 'active'::text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT products_pkey PRIMARY KEY (id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  first_name text,
  last_name text,
  phone text,
  company_name text,
  role USER-DEFINED DEFAULT 'production'::user_role,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.purchase_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  purchase_id uuid NOT NULL,
  material_id uuid NOT NULL,
  quantity numeric NOT NULL,
  unit_price numeric NOT NULL,
  line_total numeric NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT purchase_items_pkey PRIMARY KEY (id),
  CONSTRAINT purchase_items_material_id_fkey FOREIGN KEY (material_id) REFERENCES public.inventory(id),
  CONSTRAINT purchase_items_purchase_id_fkey FOREIGN KEY (purchase_id) REFERENCES public.purchases(id)
);
CREATE TABLE public.purchases (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  supplier_id uuid,
  purchase_number text NOT NULL,
  purchase_date date NOT NULL DEFAULT CURRENT_DATE,
  transport_charge numeric DEFAULT 0,
  subtotal numeric NOT NULL DEFAULT 0,
  total_amount numeric NOT NULL DEFAULT 0,
  status text DEFAULT 'pending'::text,
  notes text,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  invoice_number text,
  CONSTRAINT purchases_pkey PRIMARY KEY (id),
  CONSTRAINT purchases_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.suppliers(id)
);
CREATE TABLE public.stitching_jobs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  job_card_id uuid NOT NULL,
  received_quantity integer,
  part_quantity integer,
  border_quantity integer,
  handle_quantity integer,
  chain_quantity integer,
  runner_quantity integer,
  piping_quantity integer,
  start_date date,
  expected_completion_date date,
  notes text,
  worker_name text,
  is_internal boolean DEFAULT true,
  status USER-DEFINED DEFAULT 'pending'::job_status,
  rate numeric,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  provided_quantity integer,
  CONSTRAINT stitching_jobs_pkey PRIMARY KEY (id),
  CONSTRAINT stitching_jobs_job_card_id_fkey FOREIGN KEY (job_card_id) REFERENCES public.job_cards(id),
  CONSTRAINT stitching_jobs_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.suppliers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  contact_person text,
  phone text,
  email text,
  address text,
  materials_provided text,
  payment_terms text,
  status text DEFAULT 'active'::text,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT suppliers_pkey PRIMARY KEY (id),
  CONSTRAINT suppliers_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.transactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  date date NOT NULL DEFAULT CURRENT_DATE,
  amount numeric NOT NULL,
  type text NOT NULL,
  notes text,
  order_id uuid,
  supplier_id uuid,
  vendor_id uuid,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT transactions_pkey PRIMARY KEY (id),
  CONSTRAINT transactions_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id),
  CONSTRAINT transactions_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id),
  CONSTRAINT transactions_vendor_id_fkey FOREIGN KEY (vendor_id) REFERENCES public.vendors(id),
  CONSTRAINT transactions_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.suppliers(id)
);
CREATE TABLE public.vendors (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  contact_person text,
  phone text,
  email text,
  address text,
  service_type text,
  payment_terms text,
  status text DEFAULT 'active'::text,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT vendors_pkey PRIMARY KEY (id),
  CONSTRAINT vendors_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);