
import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { ArrowLeft, Plus } from "lucide-react";
import { v4 as uuidv4 } from "uuid";
import { Button } from "@/components/ui/button";
import { OrderDetailsForm } from "@/components/orders/OrderDetailsForm";
import { ComponentForm } from "@/components/orders/ComponentForm";
import { CustomComponentSection, CustomComponent } from "@/components/orders/CustomComponentSection";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "@/hooks/use-toast";

// Define component types for our order form
export type ComponentType = "part" | "border" | "handle" | "chain" | "runner" | "custom";

const OrderNew = () => {
  const navigate = useNavigate();
  const [submitting, setSubmitting] = useState(false);
  
  // Order details state
  const [orderDetails, setOrderDetails] = useState({
    company_name: "",
    quantity: "",
    bag_length: "",
    bag_width: "",
    rate: "",
    special_instructions: "",
    order_date: new Date().toISOString().split('T')[0],
  });

  // Standard components state
  const [components, setComponents] = useState<{
    part?: CustomComponent;
    border?: CustomComponent;
    handle?: CustomComponent;
    chain?: CustomComponent;
    runner?: CustomComponent;
  }>({});

  // Custom added components state
  const [customComponents, setCustomComponents] = useState<CustomComponent[]>([]);

  // Mock data for component options (color, gsm)
  const componentOptions = {
    color: ["White", "Black", "Red", "Blue", "Green", "Yellow"],
    gsm: ["80", "100", "120", "150", "180", "200", "250"]
  };

  const handleOrderChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => {
    const { name, value } = e.target;
    setOrderDetails((prev) => ({ ...prev, [name]: value }));
  };

  const handleComponentChange = (type: ComponentType, field: string, value: string) => {
    setComponents((prev) => {
      const component = prev[type] || { id: uuidv4(), type };
      return {
        ...prev,
        [type]: {
          ...component,
          [field]: value,
        },
      };
    });
  };

  const handleCustomComponentChange = (index: number, field: string, value: string) => {
    setCustomComponents((prev) => {
      const updated = [...prev];
      updated[index] = { ...updated[index], [field]: value };
      return updated;
    });
  };

  const addCustomComponent = () => {
    setCustomComponents([
      ...customComponents,
      { id: uuidv4(), type: "custom", customName: "" },
    ]);
  };

  const removeCustomComponent = (index: number) => {
    setCustomComponents((prev) => prev.filter((_, i) => i !== index));
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    
    // Validate required fields
    const { company_name, quantity, bag_length, bag_width } = orderDetails;
    if (!company_name || !quantity || !bag_length || !bag_width) {
      toast({
        title: "Missing required fields",
        description: "Please fill in all required order details",
        variant: "destructive",
      });
      return;
    }

    setSubmitting(true);

    try {
      // Insert order into orders table with generated order_number
      // The order_number is generated by a trigger in the Supabase database
      const { data: orderData, error: orderError } = await supabase
        .from("orders")
        .insert({
          company_name,
          quantity: parseInt(quantity),
          bag_length: parseFloat(bag_length),
          bag_width: parseFloat(bag_width),
          rate: orderDetails.rate ? parseFloat(orderDetails.rate) : null,
          order_date: orderDetails.order_date,
          special_instructions: orderDetails.special_instructions,
        })
        .select('id, order_number')
        .single();

      if (orderError) throw orderError;

      // Prepare component data for insertion
      const allComponents = [
        ...Object.values(components).filter(Boolean),
        ...customComponents,
      ].filter(Boolean);
      
      if (allComponents.length > 0) {
        for (const comp of allComponents) {
          // Define allowable component type values that match the database enum
          const componentType = comp.type === 'custom' ? 'custom' : 
            (['part', 'border', 'handle', 'chain', 'runner'].includes(comp.type) ? 
              comp.type : 'custom');

          const { error: componentError } = await supabase
            .from("components")
            .insert({
              order_id: orderData.id,
              type: componentType,
              size: (comp.length && comp.width) ? `${comp.length}x${comp.width}` : null,
              color: comp.color || null,
              gsm: comp.gsm || null,
              details: comp.type === 'custom' ? comp.customName : null
            });

          if (componentError) {
            console.error("Error saving component:", componentError);
            toast({
              title: "Error saving component",
              description: componentError.message,
              variant: "destructive",
            });
          }
        }
      }

      toast({
        title: "Order created successfully",
        description: `Order number: ${orderData.order_number}`,
      });

      // Navigate to the order detail page
      navigate(`/orders/${orderData.id}`);
    } catch (error: any) {
      console.error("Error creating order:", error);
      toast({
        title: "Error creating order",
        description: error.message,
        variant: "destructive",
      });
    } finally {
      setSubmitting(false);
    }
  };

  // Prepare components for the ComponentForm
  const getComponentWithDefaults = (componentType: ComponentType) => {
    const component = components[componentType] || { id: uuidv4(), type: componentType, width: "", length: "", color: "", gsm: "" };
    return {
      ...component,
      width: component.width || "",
      length: component.length || "",
      color: component.color || "",
      gsm: component.gsm || ""
    };
  };

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2">
          <Button
            variant="ghost"
            size="sm"
            onClick={() => navigate("/orders")}
            className="gap-1"
          >
            <ArrowLeft size={16} />
            Back
          </Button>
          <div>
            <h1 className="text-3xl font-bold tracking-tight">New Order</h1>
            <p className="text-muted-foreground">Create a new order for production</p>
          </div>
        </div>
      </div>

      <form onSubmit={handleSubmit} className="space-y-6">
        <OrderDetailsForm
          formData={orderDetails}
          handleOrderChange={handleOrderChange}
        />

        <div className="grid grid-cols-1 gap-6">
          <h2 className="text-lg font-medium">Standard Components</h2>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <ComponentForm
              title="Part"
              component={getComponentWithDefaults("part")}
              index={0}
              isCustom={false}
              componentOptions={componentOptions}
              handleChange={(index, field, value) => handleComponentChange("part", field, value)}
            />
            <ComponentForm
              title="Border"
              component={getComponentWithDefaults("border")}
              index={0}
              isCustom={false}
              componentOptions={componentOptions}
              handleChange={(index, field, value) => handleComponentChange("border", field, value)}
            />
            <ComponentForm
              title="Handle"
              component={getComponentWithDefaults("handle")}
              index={0}
              isCustom={false}
              componentOptions={componentOptions}
              handleChange={(index, field, value) => handleComponentChange("handle", field, value)}
            />
            <ComponentForm
              title="Chain"
              component={getComponentWithDefaults("chain")}
              index={0}
              isCustom={false}
              componentOptions={componentOptions}
              handleChange={(index, field, value) => handleComponentChange("chain", field, value)}
            />
            <ComponentForm
              title="Runner"
              component={getComponentWithDefaults("runner")}
              index={0}
              isCustom={false}
              componentOptions={componentOptions}
              handleChange={(index, field, value) => handleComponentChange("runner", field, value)}
            />
          </div>
        </div>

        <div className="space-y-4">
          <div className="flex items-center justify-between">
            <h2 className="text-lg font-medium">Custom Components</h2>
            <Button
              type="button"
              variant="outline"
              size="sm"
              className="flex items-center gap-1"
              onClick={addCustomComponent}
            >
              <Plus size={16} />
              Add Custom Component
            </Button>
          </div>

          <CustomComponentSection
            components={customComponents}
            onChange={handleCustomComponentChange}
            onRemove={removeCustomComponent}
          />
        </div>

        <div className="flex justify-end gap-2">
          <Button
            type="button"
            variant="outline"
            onClick={() => navigate("/orders")}
          >
            Cancel
          </Button>
          <Button type="submit" disabled={submitting}>
            {submitting ? "Creating..." : "Create Order"}
          </Button>
        </div>
      </form>
    </div>
  );
};

export default OrderNew;
